name: Documentation Change
description: Suggest a change to documentation
title: "Documentation: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us maintain the CASDK documentation! If you'd just like to fix spelling/typos in the current documentation,
        feel free to submit a pull request without raising an issue. If you'd like to change the content of current documentation,
        please submit this issue to explain the purpose of the change.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: overview
    attributes:
      label: Overview of Change
      description: Please give a brief overview of your intended change. What is the purpose of the change and what content will be impacted?
      placeholder: Explain change
      value: "Describe change"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow the [Way We Work](https://github.com/Green-Software-Foundation/standards_wg/blob/main/the_way_we_work.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true