name: Publish container image to GitHub Packages

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  detect-current-api-version:
    uses: ./.github/workflows/detect-webapi-version.yaml
    with:
      # We cannot use environment variables here due to workflow limitation.
      # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#limitations
      registry: ghcr.io
      image-repo: ${{ github.repository }}

  publish-container-image:
    runs-on: ubuntu-latest
    needs: detect-current-api-version
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          flavor: latest=true
          tags: type=raw,value=${{ github.ref_name }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: "{{defaultContext}}:src"
          file: CarbonAware.WebApi/src/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false

  detect-newer-api-version:
    needs: publish-container-image
    uses: ./.github/workflows/detect-webapi-version.yaml
    with:
      # We cannot use environment variables here due to workflow limitation.
      # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#limitations
      registry: ghcr.io
      image-repo: ${{ github.repository }}

  generate-webapi-clients:
    needs:
      - detect-current-api-version
      - detect-newer-api-version
    if: ${{ needs.detect-current-api-version.outputs.apiver != needs.detect-newer-api-version.outputs.apiver }}
    uses: ./.github/workflows/4.a-generate-webapi-clients.yaml
    permissions:
      contents: write
      packages: write
      pull-requests: write
    with:
      # We cannot use environment variables here due to workflow limitation.
      # https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/reusing-workflows#limitations
      registry: ghcr.io
      image-repo: ${{ github.repository }}
