# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: 6-Deploy docs to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["dev", "docs/*"]
    paths:
      - 'casdk-docs/**'
      - 'samples/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete. 
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
   deploy:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
    
      - name: Copy Files
        run: |
          # Moving the samples folder at build& deploy time of the docs so that it appears in the end result
          cp -r ./samples/ ./casdk-docs/docs/
          cp -r ./README.md ./casdk-docs/docs/overview/overview.md
          cp -r ./CONTRIBUTING.md ./casdk-docs/docs/overview/contributing.md
        working-directory: .

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./casdk-docs
      - name: Build website
        run: yarn build
        working-directory: ./casdk-docs

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./casdk-docs/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
